### ISSUE TITLE
BAASSSHHHHH!!!

### ISSUE THREAD

**Issue by IGBC** [spacekookie/ssh-poke#22]
>  - or open a ticket for your favourite...

BAASSSHHHHH!!!!
BAASSSHHHHH!!!!
BAASSSHHHHH!!!!
BAASSSHHHHH!!!!
BAASSSHHHHH!!!!
BAASSSHHHHH!!!!

Okay flame war over, please include support for bash, as it by far the most popular shell out there, remaining the default on the majority of modern GNU/Linux Distributions.

**Comment by spacekookie** [comment]
___					
	      /  ;  				
	  _.--"""-..   _.		
	 /ö         `-'  [	
	]  ,    ,    ,   ;	
	 '--L__J_.-""',_;	
	     '-._J
